### ISSUE TITLE
Selenium installation error: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by metaodi** [metaodi/website-monitor#11]
The latest selenium package has an error:

```
Traceback (most recent call last):
  File "./lib/website_hash.py", line 30, in <module>
    import download as dl
  File "/home/runner/work/website-monitor/website-monitor/lib/download.py", line 6, in <module>
    from selenium import webdriver
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/selenium/webdriver/__init__.py", line 29, in <module>
    from .firefox.firefox_profile import FirefoxProfile  # noqa
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 31, in <module>
    from typing_extensions import deprecated
ModuleNotFoundError: No module named 'typing_extensions'
Error: Process completed with exit code 1.
```

**Comment by metaodi** [comment]
Selenium has an issue for it: https://github.com/SeleniumHQ/selenium/issues/13486

**Comment by metaodi** [comment]
I simply pinned the version to selenium 4.16.0: https://github.com/metaodi/website-monitor/commit/67cf60c95ddc60ba1122262192b396fa75990cf6
